"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Game_1 = require("./components/Game");
exports.GameComponent = Game_1.GameComponent;
var utils_1 = require("./components/Game/utils");
exports.setCellSize = utils_1.setCellSize;
var common_1 = require("./utils/common");
exports.getRandomNum = common_1.getRandomNum;
var drawing_1 = require("./utils/drawing");
exports.drawCircle = drawing_1.drawCircle;
exports.drawSector = drawing_1.drawSector;
exports.drawArc = drawing_1.drawArc;
exports.drawLineToAngle = drawing_1.drawLineToAngle;
exports.drawRectangle = drawing_1.drawRectangle;
exports.drawTriangle = drawing_1.drawTriangle;
exports.drawStar = drawing_1.drawStar;
var math_1 = require("./utils/math");
exports.lineSegmentsIntersect = math_1.lineSegmentsIntersect;
exports.pointOnLineSegment = math_1.pointOnLineSegment;
exports.lineSegmentIntersectsWithRect = math_1.lineSegmentIntersectsWithRect;
var storage_1 = require("./utils/storage");
exports.getStorageData = storage_1.getStorageData;
exports.saveStorageData = storage_1.saveStorageData;
exports.removeStorageData = storage_1.removeStorageData;
